FROM php:7-apache

# Setup Apache2 config
COPY 000-default.conf /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite

# Create user - replace 1000 with your $UID and $GID
RUN groupadd apache-www-volume -g 1000
RUN useradd apache-www-volume -u 1000 -g apache-www-volume

# INSTALL COMPOSER and libraries

# Copy application source
# COPY src /var/www/
# RUN chown -R www-data:www-data /var/www

# EXPOSE 80
# EXPOSE 443
CMD ["apache2-foreground"]
